### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by dhtveso** [SoftUniHW/Github#1]
Дайте някакви контакти да се чуем и да обсъдим задачата!

**Comment by Silvena** [comment]
skype: silveria_d1

2017-10-16 22:12 GMT+03:00 Veselin Milyovski <notifications@github.com>:

**Comment by StoyanZhulev** [comment]
Дайте фейсбук ако имате че ще е по лесно

На 16.10.2017 г. 10:38 сл.об. "Silvena Shtereva" <notifications@github.com>
написа:

**Comment by Silvena** [comment]
fb: Marquis Fleur   /аватара е лъв/

2017-10-16 22:47 GMT+03:00 StoyanZhulev <notifications@github.com>:

**Comment by dhtveso** [comment]
Facebook chat - Teamwork
